const destinations: string[] = [
  'Atlanta',
  'Chicago',
  'Beijing',
  'London',
  'Paris',
  'Los Angeles',
  'Frankfurt',
  'Dallas-Fort Worth',
  'New York',
  'Amsterdam',
  'Shanghai',
  'Singapore',
  'Barcelona',
  'Seoul',
  'Denver',
  'Miami',
  'Munich',
  'Istanbul',
  'Hong Kong',
  'Dubai',
  'London',
  'Guangzhou',
  'Rome',
  'Madrid',
  'Bangkok',
  'Moscow',
  'Chengdu',
  'Toronto',
  'Brussels',
  'Manchester',
  'Vienna',
  'Charlotte',
  'Philadelphia',
  'Tokyo',
  'Duesseldorf',
  "Xi'an",
  'Palma de Mallorca',
  'Kunming',
  'Chongqing',
  'Delhi',
  'Taipei',
  'Kuala Lumpur',
  'Phoenix',
  'Hangzhou',
  'Newark',
  'San Francisco',
  'Las Vegas',
  'Zurich',
  'Houston',
  'Mexico City',
  'Abu Dhabi',
  'Orlando',
  'Shenzhen',
  'Xiamen',
  'Copenhagen',
  'Mumbai',
  'Stockholm',
  'Lisbon',
  'Detroit',
  'Minneapolis',
  'Boston',
  'Berlin',
  'Dublin',
  'Shanghai',
  'Sydney',
  'Malaga',
  'Paris',
  'Athens',
  'Seattle',
  'Moscow',
  'Washington',
  'Sao Paulo',
  'Washington',
  'Manila',
  'Milano',
  'Changcha',
  'Doha',
  'Jeddah',
  'Qingdao',
  'Fort Lauderdale',
  'Wuhan',
  'Montreal',
  'St. Petersburg',
  'Jakarta',
  'Oslo',
  'Prague',
  'Zhengzhou',
  'London',
  'Nanjing',
  'Geneva',
  'Johannesburg',
  'Hamburg',
  'Helsinki',
  'Tenerife',
  'New York',
  'Tokyo',
  'Vancouver',
  'Alicante',
  'Cancun',
  'Gran Canaria',
  'Bogota',
  'Urumqi',
  'Osaka',
  'Cairo',
  'Brisbane',
  'Tianjin',
  'Istanbul',
  'Baltimore',
  'Dalian',
  'Salt Lake City',
  'Tampa',
  'Riyadh',
  'Lyon',
  'Guiyang',
  'Stuttgart',
  'Shenyang',
  'Chicago',
  'Tel-aviv',
  'Jinan',
  'Melbourne',
  'Nice',
  'Fuzhou',
  'Cologne',
  'Marseille',
  'Birmingham',
  'Harbin',
  'Nairobi',
  'Antalya',
  'Casablanca',
  'New Orleans',
  'Venice',
  'Warsaw',
  'Kuwait',
  'San Diego',
  'Edinburgh',
  'Honolulu',
  'Catania',
  'Las Palmas',
  'Portland',
  'Lima',
  'Nanning',
  'Calgary',
  'Bucharest',
  'Malta',
  'Amman',
  'St. Louis',
  'Taiyuan',
  'Heraklion',
  'Sanya',
  'Ho Chi Minh City',
  'Haikou',
  'London',
  'Guilin',
  'Addis Ababa',
  'Auckland',
  'Panama City',
  'Madras',
  'Faro',
  'Muscat',
  'San Juan',
  'Colombo',
  'Riga',
  'Kiev',
  'Porto',
  'Ibiza',
  'Denpasar',
  'Bristol',
  'Yekaterinburg',
  'Brasilia',
  'Glasgow',
  'Bangalore',
  'Sharjah',
  'Budapest',
  'Kolkata',
  'Rio De Janeiro',
  'East Midlands',
  'Fuerteventura',
  'Larnaca',
  'Basel',
  'Guadalajara',
  'Nantes',
  'Perth',
  'Caracas',
  'Novosibirsk',
  'Algier',
  'Bologna',
  'Tunis',
  'Hohhot',
  'Hanoi',
  'Thessaloniki',
  'Nanchang',
  'Moscow',
  'Belgrade',
  'Fukuoka',
  'Bahrain',
  'Nagoya',
  'Lanzhou',
  'Ninbo',
  'Charleroi',
  'Rhodos',
  'Austin',
  'Raleigh-durham',
  'Newcastle',
  'Berlin',
  'Shijiazhuang',
  'Nashville',
  'Dammam',
  'Valencia',
  'Wenzhou',
  'Sapporo',
  'Bergamo',
  'Cleveland',
  'Toulouse',
  'Beijing',
  'Leeds',
  'Tashkent',
  'Busan',
  'Kansas City',
  'Macau',
  'Santiago',
  'Naples',
  'Hefei',
  'Hannover',
  'Pisa',
  'Cincinnati',
  'Buenos Aires',
  'Houston',
  'San Jose',
  'Pittsburgh',
  'Dhaka',
  'Hyderabad',
  'Monterrey',
  'Marrakech',
  'Punta Cana',
  'Luxemburg',
  'Edmonton',
  'Indianapolis',
  'Phuket',
  'Bergen',
  'San Antonio',
  'Eindhoven',
  'Nassau',
  'Bangkok',
  'Alma-ata',
  'Bordeaux',
  'Dakar',
  'Beirut',
  'Izmir',
  'Sofia',
  'Changchun',
  'Yinchuan',
  'Surabaya',
  'Lijiang',
  'Kaohsiung',
  'London',
  'Mashhad',
  'Fort Myers',
  'Columbus',
  'Baku',
  'Buenos Aires',
  'Bilbao',
  'Sevilla',
  'Palermo',
  'Milwaukee',
  'Karachi',
  'Teheran',
  'Okinawa',
  'Tehran',
  'Dubrovnik',
  'San Jose',
  'Milan',
  'Beauvais',
  'Zhuhai',
  'Lagos',
  'Anchorage',
  'Kochi',
  'Cheju',
  'Islamabad',
  'Liverpool',
  'Vilnius',
  'Salvador',
  'Dalaman',
  'Krakow',
  'Philipsburg',
  'Campinas',
  'Memphis',
  'Yantai',
  'Ujung Pandang',
  'Oakland',
  'Lahore',
  'Cairns',
  'Belo Horizonte',
  'Sacramento',
  'Minsk 2',
  'Accra',
  'Gothenborg',
  'Stavanger',
  'Dushanbe',
  'Florence',
  'San Salvador',
  'Ankara',
  'Funchal',
  'Kota Kinabalu',
  'Tselinograd',
  'Olbia',
  'Windsor Locks',
  'Kerkyra/corfu',
  'Port Moresby',
  'Adelaide',
  'Abidjan',
  'Gdansk',
  'San Jose Del Cabo',
  'Bremen',
  'Rome',
  'Bari',
  'Xining',
  'Yangon',
  'Douala',
  'Madinah',
  'Gerona',
  'Cebu',
  'Sanford',
  'Split',
  'Halifax',
  'Chiang Mai',
  'Nuernberg',
  'Tripoli',
  'Wuxi',
  'Billund',
  'Hahn',
  'Sao Paulo',
  'Santo Domingo',
  'Luanda',
  'Dubai',
  'Krasnoyarsk',
  'Puerto Vallarta',
  'Jacksonville',
  'Krasnodar',
  'Keflavik',
  'Enfidha',
  'Darwin',
  'Yerevan',
  'Bishkek',
  'Oranjestad',
  'Chania',
  'Kos',
  'Montego Bay',
  'Ottawa',
  'Quanzhou',
  'West Palm Beach',
  'Kathmandu',
  'Havana',
  'Cape Town',
  'Trondheim',
  'Santa Ana',
  'Porto Alegre',
  'Curitiba',
  'Torino',
  'Cagliari',
  'Male',
  'Zagreb',
  'Paphos',
  'Kahului',
  'Penang',
  'Trivandrum',
  'Osaka',
  'Albuquerque',
  'Louisville',
  'Nandi',
  'Tijuana',
  'Plaisance',
  'Aberdeen',
  'Irkutsk',
  'Oklahoma City',
  'Alexandria',
  'Siem-reap',
  'Winnipeg',
  'Khartoum',
  'Cotonou',
  'Taipei',
  'Lille',
  'Leipzig',
  'Hurghada',
  'Quito',
  'Seoul',
  'Shiraz',
  'Ajaccio',
  'Kigali',
  'Papeete',
  'Sharm El Sheikh',
  'Guatemala City',
  'Villafranca',
  'Jersey',
  'Weeze',
  'Tallinn-ulemiste International',
  'Richmond',
  'Yakutsk',
  'Treviso',
  'Sanaa',
  'Dallas',
  'Khabarovsk',
  'Sandefjord',
  'Rygge',
  'Changzhou',
  'Norfolk',
  'Djerba',
  'Balikpapan',
  'Recife',
  'Christchurch',
  'Bastia',
  'Tirana',
  'Shantou',
  'Buffalo',
  'Birmingham',
  'Guayaquil',
  'Fortaleza',
  'Belfast',
  'Ahmedabad',
  'Port-of-spain',
  'Belem',
  'Agana',
  'Santiago',
  'Menorca',
  'Tbilisi',
  'Charleston',
  'Omaha',
  'Antigua',
  'Salzburg',
  'Strasbourg',
  'Cork',
  'Myrtle Beach',
  'Pune',
  'Oran',
  'Chisinau',
  'Lusaka',
  'Dortmund',
  'Entebbe',
  'Dar Es Salaam',
  'Wroclaw',
  'Khudzhand',
  'Rotterdam',
  'Southampton',
  'Danang',
  'St. Thomas',
  'Cuiaba',
  'Ouagadougou',
  'Ljubljana',
  'Tenerife',
  'Mesa',
  'Dayton',
  'Manaus',
  'Wellington',
  'Guwahati',
  'Cardiff',
  'Bodrum',
  'Willemstad',
  'Stockholm',
  'Knoxville',
  'Tucson',
  'St. Petersburg',
  'Sendai',
  'Providenciales',
  'Alghero',
  'Calicut',
  'Phnom-penh',
  'Rio De Janeiro',
  'Lhasa',
  'Erbil',
  'Albany',
  'Rochester',
  'Osh',
  'Abuja',
  'Peshawar',
  'Yuncheng',
  'Baotou',
  'Shannon',
  'Greenville',
  'Yogyakarta',
  'Little Rock',
  'Kuala Lumpur',
  'Goa',
  'Pointe-a-pitre',
  'Taichung',
  'Yellowknife',
  'Kingston',
  'Des Moines',
  'Bethel',
  'Cali',
  'Quebec',
  'Harare',
  'Katowice',
  'Reno',
  'Grand Rapids',
  'Coolangatta',
  'Kazan',
  'Rostov',
  'Port-vila',
  'Belize City',
  'Trapani',
  'Agadir',
  'Tulsa',
  'Providence',
  'Bamako',
  'Kinshasa',
  'Antananarivo',
  'Stockholm',
  'Samara',
  'Batam',
  'Fairbanks',
  'Kabul',
  'Warsaw',
  'Tromso',
  'Huangshan',
  'Syracuse',
  'Kuching',
  'Sochi',
  'Vladivostok',
  'Rio Negro',
  'Zadar',
  'Brazzaville',
  'Greensboro',
  'Palm Springs',
  'La Paz',
  'Georgetown',
  'Dongsheng',
  'Ontario',
  'Vientiane',
  'Lamezia',
  'Benghazi',
  'Exeter',
  'Nome',
  'Libreville',
  'Yichang',
  'Bentonville',
  'Honiara',
  'Jinghong',
  'Miri',
  'Santa Cruz',
  'Ahwaz',
  'Port-au-prince',
  'Hermosillo',
  'Skopje',
  'Montpellier',
  'Rankin Inlet',
  'El Paso',
  'Ponta Delgada',
  'Memmingen',
  'Savannah',
  'White Plains',
  'Bandar Seri Begawan',
  'Ufa',
  'Fort-de-france',
  'Bridgetown',
  'Montevideo',
  'San Pedro Sula',
  'Tyumen',
  'Kotzebue',
  'Liberia',
  'Akron',
  'Aden',
  'Ketchikan',
  'Dresden',
  'Mineralnye Vody',
  'Kiev',
  'Sept-iles',
  'Brindisi',
  'Freetown',
  'Mianyang',
  'Goiania',
  "St. John's",
  'Jerez',
  'Durban',
  'Gothenborg',
  'Poznan',
  'Dayong',
  'Prestwick',
  'Belfast',
  'Aktau',
  'Bandung',
  'Lihue',
  'Pensacola',
  'Manado',
  'Florianopolis',
  'Pristina',
  'Cluj-napoca',
  'Aalborg',
  'Kona',
  'Boise',
  'Ulan Bator',
  'Lome',
  'Kilimanjaro',
  'St.-denis',
  'Beihai',
  'Karlsruhe/Baden-Baden',
  'Isfahan',
  'Xuzhou',
  'Djibouti',
  'Lexington KY',
  'Manchester NH',
  'Fresno',
  'Juneau',
  'Wichita',
  'Chelyabinsk',
  'Bratislava',
  'Genoa',
  'Calvi',
  'Murcia',
  'Harrisburg',
  'Porlamar',
  'Reus',
  'Zhanjiang',
  'Bournemouth',
  'Yaounde',
  'Windhoek',
  'Kaunas',
  'Ribeirao Preto',
  'Bandar Abbas',
  'Graz',
  'Santander',
  'Tanger',
  'Odessa',
  'Hewandorra',
  'Nairobi',
  'Yangzhou',
  'Pointe-noire',
  'Yiwu',
  'Linyi',
  'El Aroui',
  'Iqaluit',
  'Nantong',
  'Guernsey',
  'Nizhniy Novgorod',
  'Conakry',
  'Huntsville',
  'Burbank',
  'Long Beach',
  'Jackson',
  'Hailar',
  'Johor Bahru',
  'Pekanbaru',
  'Ko Samui',
  'Lucknow',
  'Vishakhapatnam',
  'Asuncion',
  'Kalibo',
  'Kagoshima',
  'Tegucigalpa',
  'Almeria',
  'Fes',
  'Punta Gorda',
  'Bodo',
  'Cedar Rapids',
  'Jayapura',
  'Dominica',
  'Amilcar Cabral',
  'Maputo',
  'Yancheng',
  'Praia',
  'Semarang',
  'Columbia',
  'Madison',
  'Pulau',
  'Coimbatore',
  'Jaipur',
  'Omsk',
  'Lvov',
  'Niamey',
  'Campo Grande',
  'Hiroshima',
  'Kanazawa',
  'Nagasaki',
  'Sioux Lookout',
  'Adana',
  'Brest',
  'Aviles',
  'Key West',
  'Islip',
  'Mandalay',
  'Yuzhno-sakhalinsk',
  'Kish Island',
  'Chihuahua',
  'Zakynthos',
  'Regina',
  'Praya',
  'Malmoe',
  'Lianyungang',
  'Jingdezhen',
  'Changzhi',
  'Niigata',
  'Novy Urengoy',
  'Jiuzhaigou',
  'Fort Wayne',
  'Chattanooga',
  'Townsville',
  'Krabi',
  'Chittagong',
  'Baghdogra',
  'Indore',
  'Vitoria',
  'Natal',
  'Constantine',
  'Vera Cruz',
  'Cozumel',
  'Culiacan',
  'Podgorica',
  'Sarajevo',
  'Monrovia',
  'Mangalore',
  'Monastir',
  'Sao Luis',
  'Wabush',
  'Thira',
  'Dzaoudzi',
  'Kelowna',
  'Wuyishan',
  'Chifeng',
  'Connaught',
  'Moline',
  'Bermuda',
  'Peoria',
  'Roanoke VA',
  'Tallahassee',
  'Spokane',
  'Nagpur',
  'Ashkhabad',
  'Kaliningrad',
  'Donetsk',
  'Uberlandia',
  'Tabriz',
  'Freeport',
  'Goose Bay',
  'Mazatlan',
  'Merida',
  'Saskatoon',
  'Pula',
  'Norilsk',
  'Banjarmasin',
  'Srinagar',
  'Point Salines',
  'Abha',
  'Managua',
  'Del Bajio',
  'Puerto Plata',
  'Malabo',
  'Yanji',
  'Huangyan',
  'Liuzhou',
  'Nicosia',
  'Southend',
  'Springfield',
  'Fargo',
  'Baghdad',
  'Santarem',
  'Davao',
  'Trenton',
  'Kota Bahru',
  'Ambon',
  'Surgut',
  'Nizhnevartovsk',
  'Dnepropetrovsk',
  'Maracaibo',
  'Ishigaki',
  'Quetta',
  'Marsh Harbor',
  'Roatan',
  'Toronto',
  'Figari',
  'Biarritz-bayonne',
  'Boa Vista',
  'Eugene',
  'Colorado Springs',
  'Burlington',
  'Palembang',
  'Avarua',
  'Toluca',
  'Thunder Bay',
  'Bujumbura',
  'Mahe',
  'Luzhou',
  'Zhoushan',
  'Ganzhou',
  'Xiangfan',
  'Tongliao',
  'Alesund',
  'Allentown',
  'Angeles City',
  'Flint',
  'Sarasota',
  'Charlottesville VA',
  'Sioux Falls',
  'Wilmington',
  'Friedrichshafen',
  'Kashi',
  'Canberra',
  'Mount Isa',
  'Luang Prabang',
  'Maceio',
  'Aracaju',
  'Cordoba',
  'Okayama',
  'Taif',
  'Noumea',
  'Villahermosa',
  'Victoria',
  'Timisoara',
  'Mykonos',
  'Rennes',
  'Mombasa',
  'Banjul',
  'Fort Mcmurray',
  'Aniak',
  'Tokua',
  'Patina',
  'Belo Horizonte',
  'Gassim',
  'Lilongwe',
  'Huai An',
  'Haugesund',
  'Wanxian',
  'Yulin',
  'Namangan',
  'Misratah',
  'Mogadishu',
  'Tampere',
  'Broome',
  'Bloomington',
  'Billings',
  'Asheville',
  'Kobe',
  'Gainesville',
  'Alice Springs',
  'Jammu',
  'Tortola',
  'Cartagena',
  'Foz Do Iguacu',
  'Matsuyama',
  'Multan',
  'Varadero',
  'Ciudad Juarez',
  'Bern',
  'Iasi',
  'La Coruna',
  'Bourgas',
  'Zanzibar',
  'Juba',
  'Sialkot',
  'Londrina',
  'Nausori',
  'Linz',
  'Mulhouse',
  'Nouakschott',
  'Fuyang',
  'Manzhouli',
  'Rzeszow',
  'Kristiansand',
  'Datong',
  'Belgorod',
  'Santo',
  'Kirkwall',
  'Isle Of Man',
  'South Bend',
  'San Pedro',
  'Nadzab',
  'Mukalla',
  'Chiang Rai',
  'Paderborn',
  'Munster',
  'Port Blair',
  'Raipur',
  'Mount Hagen',
  'Ulan-ude',
  'Chita',
  'Basse Terre',
  'Guayana',
  'Barcelona',
  'Cuzco',
  'San Andres Island',
  'Medellin',
  'Antofagasta',
  'Teresina',
  'Maraba',
  'Joao Pessoa',
  'Miyazaki',
  'Zahedan',
  'Santiago',
  'Tivat',
  'Lajes (terceira Island)',
  'Ronchi De Legionari',
  'Preveza',
  'Limoges',
  'Bergerac',
  'Vigo',
  'Rabat',
  'Najaf',
  'Gustavia',
  'Inverness',
  'Charleston',
  'Porto Seguro',
  'Kupang',
  'Valparaiso',
  'Ranchi',
  'Chimkent',
  'Castries',
  'Mendoza',
  'Moroni',
  'Ndola',
  'Unalakleet',
  'Jining',
  'Hami',
  'La Rochelle',
  'Shizuoka',
  'Jiamusi',
  'Korla',
  'Alta',
  'Sulaymaniyah',
  'Norwich',
  'Atyrau',
  'Mudanjiang',
  'Ancona',
  'Yibin',
  'Monterey',
  'Portland',
  'Bellingham',
  'Atlantic City',
  'Varanasi',
  'Volgograd',
  'Sfax',
  'Valencia',
  'Arequipa',
  'Zandery',
  'Barranquilla',
  'Puerto Montt',
  'Maringa',
  'Iloilo',
  'Hakodate',
  'Saipan',
  'Rasht',
  'Holguin',
  'Torreon',
  'Morelia',
  'La Paz',
  'La Romana',
  'Trabzon',
  'Prince George',
  'Mytilini',
  'Kalamata',
  'Carcassonne',
  'Moncton',
  'Luxor',
  'Oujda',
  'Lubumashi',
  "N'djamena",
  'Kharkov',
  'Maastricht',
  'Scranton',
  'Amarillo',
  'Lubbock',
  'Cochabamba',
  'Iquique',
  'Babelthuap',
  'Yenbo',
  'Quujjuaq',
  'Nampula',
  'Gaberone',
  'Port Elizabeth',
  'Sohag',
  'Godthaab',
  'Hatay',
  'Ji An',
  'Harstad/Narvik',
  'Dazhou',
  'Chongju',
  'Doncaster',
  'Upernavik',
  'Blackpool',
  'Arkhangelsk',
  'Luoyang',
  'Medford',
  'Appleton',
  'Gulfport',
  'Evansville',
  'Mobile',
  'Farmington',
  'Newport News',
  'Saarbruecken',
  'Hobart',
  'Sibu',
  'Tiruchirappalli',
  'Chandigarh',
  'Amritsar',
  'Imphal',
  'Syktyvkar',
  'Kralendijk',
  'St. Croix Island',
  'Porto Velho',
  'Ilheus',
  'Puerto Princesa',
  'Toyama',
  'Kumamoto',
  'Oita',
  'Annaba',
  'Tabuk',
  'Great Exuma',
  'Santa Clara',
  'Panama',
  'Zihuatanejo',
  'Aguascalientes',
  'Gaziantep',
  'Pescara',
  'Samos',
  'Beziers',
  'Clermont-Ferrand',
  'Granada',
  'Varna',
  'Belize',
  'Charlestown',
  'Midland',
  'Kodiak',
  'Liege',
  'Bhubaneswar',
  'Mirnyj',
  'Queenstown International',
  'Noumea',
  'Acapulco',
  'Pemba',
  'Comiso',
  'Bijie',
  'Sondrestrom',
  'Visby',
  'Umea',
  'Wuhai',
  'Setif',
  'Qiqihar',
  'Guangyuan',
  'Nanyang',
  'Changde',
  'Nadym',
  'Khanty-Mansiysk',
  'Salekhard',
  'Pasco',
  'Ust Kamenogorsk',
  'Aarhus',
  'Pierre',
  'Fayetteville',
  'Gheshm',
  'Red Lake',
  'Inuvik',
  'Turku',
  'Hammerfest',
  'Newcastle',
  'Georgetown',
  'Redmond-Bend',
  'Westerland',
  'Rapid City',
  'Grand Junction',
  'Bozeman',
  'Kutaisi',
  'Santa Barbara',
  'Solo City',
  'Baton Rouge',
  'Green Bay',
  'Shreveport',
  'Lansing',
  'Bangor',
  'Port Hedland',
  'Kununurra',
  'Launceston',
  'Sorong',
  'Ternate',
  'Heho',
  'Madurai',
  'Agartala',
  'Voronezh',
  'Astrakhan',
  'Trinidad',
  'Tarija',
  'Villavicencio',
  'Port Hartcourt',
  'Sao Jose Do Rio Preto',
  'Akita',
  'Takamatsu',
  'Miho',
  'Basrah',
  'Madang',
  'North Eleuthera',
  'Mont Joli',
  'Churchill',
  'Tuxtla Gutierrez',
  'San Luis Potosi',
  'Reynosa',
  'Innsbruck',
  'Zaragoza',
  'Santa Cruz De La Palma',
  'Vaxjo',
  'Kristiansund',
  'Urgench',
  'Deer Lake',
  'Asmara',
  'Harlingen',
  'Palu',
  'Orenburg',
  'Samarkand',
  'La Ceiba',
  'Kayseri',
  'Berbera',
  'Hargeisa',
  'Tete',
  'Beira',
  'Livingstone',
  'Maun',
  'Qianjiang',
  'Uummannaq',
  'Panama City',
  'Dangriga',
  'Nizhnekamsk',
  'Szczecin',
  'Molde',
  'Jiayuguan',
  'Qinhuangdao',
  'Anqing',
  'Weifang',
  'Shangri-La',
  'Xilinhot',
  'Ulanhot',
  'Hamilton Island',
  'Vinh',
  'Nha Trang',
  'Buonmethuot',
  'Fergana',
  'Cherepovets',
  'Cayo Coco',
  'Bissau',
  'Kuujjuarapik',
  'Qaqortoq',
  'Eskimo Point',
  'Jacksonville NC',
  'Karaganda',
  'Vadso',
  'Klagenfurt',
  'Dunhuang',
  'Santa Cruz',
  'Missoula',
  'Palmas',
  'BRISTOL',
  'MONTGOMERY',
  'Dali',
  'Taiz',
  'Taraken',
  'Pangkalan Bun',
  'Pangkal Pinang',
  'Great Falls',
  'King Salmon',
  'Plattsburgh',
  'Galena',
  'Bush Field',
  'Karratha',
  'Mackay',
  'Kuala Terengganu',
  'Padang',
  'Tawau',
  'Bintulu',
  'Manokwari',
  'Silchar',
  'Udaipur',
  'Bhopal',
  'Murmansk',
  'Simferopol',
  'Aktyubinsk',
  'Iquitos',
  'Cayenne',
  'Kano',
  'La Serena',
  'Navegantes',
  'Imperatriz',
  'San Carlos De Bariloche',
  'Comodoro Rivadavia',
  'Rosario',
  'Ladag',
  'Asahikawa',
  'Salalah',
  'Yazd',
  'Manzanillo',
  'Zacatecas',
  'Tampico',
  'Queretaro',
  'Puebla',
  'Diyabakir',
  "Val D'or",
  'Poitiers',
  'Rijeka',
  'Comox',
  'Victoria Falls',
  'Toamasina',
  'Mattala',
  'Kulyab',
  'Placencia',
  'Kirkenes',
  'Groningen',
  'Nyuang U',
  'Barrow',
  'Fort Yukon',
  'Bukhara',
  'Juliaca',
  'Punta Arenas',
  'Calama',
  'Karpathos',
  'Keffallinia',
  'Thompson',
  'Natashquan',
  'Yichun',
  'Lensk',
  'Tangshan',
  'Lublin',
  'Jixi',
  'Handan',
  'Alanya',
  'Xingyi',
  'Barreiras',
  'Lulea',
  'Stebbins',
  'Gallivare',
  'Show Low',
  'Alamosa',
  'Santa Rosa',
  'Vieques Island',
  'Gorgan',
  'Navoi',
  'Dibrugarh',
  'Nanchong',
  'Quzhou',
  'Jiujiang',
  'Luxi',
  'Qingyang',
  'Port Macquarie',
  'Mildura',
  'Vitória Da Conquista',
  'Kerry',
  'Wewak',
  'Nagoya',
  'Mcgrath',
  'Lar',
  'Dasht-e-naz',
  'Samana',
  'Asyut',
  'Ondjiva',
  'Waskaganish',
  'Chesterfield Inlet',
  'Caye Caulker',
  'Hoskins',
  'Newquai',
  'Marsa Alam',
  'Kalymnos',
  'Muan',
  'Dongying',
  'Sandakan',
  'Page',
  'Bismarck',
  'Mulu',
  'Kalamazoo',
  'Batumi',
  'Elmira',
  'Wilmington',
  'Alexandria',
  'Mcallen',
  'Cheyenne',
  'Santa Fe',
  'Killeen',
  'Monroe',
  'Newburgh',
  'Bakersfield',
  'Nantucket',
  'Lafayette',
  'Hotan',
  'Erfurt',
  'Jambi',
  'Pontianak',
  'Marudi',
  'Cambridge Bay',
  'Udon Thani',
  'Hat Yai',
  'Leh',
  'Jodhpur',
  'Aizwal',
  'Campbell River',
  'Perm',
  'Petropavlovsk',
  'Magadan',
  'The Valley',
  'Baker Lake',
  'Tarapoto',
  'Pucallpa',
  'Sucre',
  'Quibdo',
  'Pereira',
  'Leticia',
  'Baie Comeau',
  'Neuquen',
  'Salta',
  'Bacolod',
  'Zamboanga',
  'Taegu',
  'Hassi Messaoud',
  'Tlemcen',
  'Memanbetsu',
  'Chah Bahar',
  'Bakhtaran',
  'Abadan',
  'Bejaja',
  'Gizan',
  'Herat',
  'Bora Bora',
  'Poza Rico',
  'Oaxaca',
  'London',
  'Gibraltar',
  'Elazig',
  'Fort Saint John',
  'Horta',
  'Norman Wells',
  'Reggio Calabria',
  'Leros',
  'Kavala',
  'Chios',
  'Mwanza',
  'Wajir',
  'Sao Vicente Island',
  'Shaktoolik',
  'Zweibruecken',
  'Aksu',
  "Yan'an",
  'Bandar Lampung-Sumatra Island',
  'Turbat',
  'Bahawalpur',
  'Whale Cove',
  'Gurney',
  'Coral Harbour',
  'Deadhorse',
  'Concepcion',
  'Rio Gallegos',
  'Trelew',
  'Ouargla',
  'Adrar',
  'Sukkur',
  'Rangiroa',
  'Faleolo',
  'Santiago De Cuba',
  'Kosice',
  'Timmins',
  'Sudbury',
  'Brive',
  'Antsiranana',
  'Sanliurfa',
  'Baishan',
  'Bayannur',
  'Belmopan',
  'George',
  'East London',
  'Schefferville',
  'Tengchong',
  'Kamloops',
  'Laage',
  'Angmagssalik',
  'Khalije Fars',
  'Sundsvall',
  'Koyuk',
  'Hollis',
  'Craig',
  'Halmstad',
  'Narssarssuaq',
  'Tongren',
  'Mardin',
  "St Mary's",
  'Dandong',
  'Jinzhou',
  'Nyingchi',
  'Meixian',
  'Bronnoysund',
  'Gove',
  'Cloncurry',
  'Khanabad',
  'Sovetskiy',
  'Yakutia',
  'Juazeiro Do Norte',
  'General Santos City',
  'Kushiro',
  'Sayun Intl',
  'Norsup',
  'Huntington',
  'Dodge City',
  'Port Sudan',
  'Malindi',
  'Heringsdorf',
  'The Pas',
  'Igloolik',
  'Momote',
  'Girua',
  'Stornoway',
  'Sumburgh',
  'Humberside',
  'Londonderry',
  'Vaasa',
  'Noyabrsk',
  'Saratov',
  'Liberal',
  'Mehamn',
  'State College Pennsylvania',
  'Tomsk',
  'Ballina Byron Bay',
  'Kulusuk',
  'Tanna',
  'Phu Quoc',
  'Dalat',
  'Saginaw',
  'Kalispell',
  'Wassau',
  'Toledo',
  'Rockford',
  'Traverse City',
  'Ilulissat',
  'Daytona Beach',
  'Cold Bay',
  'Corpus Christi',
  'New Bern',
  'Durango',
  'Coppermine',
  'Melbourne',
  'Niagara Falls',
  'Minot',
  'Grand Forks',
  'Fort Smith',
  'Xichang',
  'Pyongyang',
  'Kalgoorlie',
  'Rockhampton',
  'Maroochydore',
  'Kuantan',
  'Alor Setar',
  'Banda Aceh',
  'Bengkulu',
  'Thimphu',
  'Pakse',
  'Dehra Dun',
  'Sylhet Osmani',
  'Baroda',
  'Aurangabad',
  'Blagoveschensk',
  'Barquisimeto',
  'Bucaramanga',
  'Tefe',
  'Rio Branco',
  'Petrolina',
  'Passo Fundo',
  'Joinville',
  'Chapeco',
  'Ushuaia',
  'Tacloban',
  'Miyako',
  'Aomori',
  'Ibaraki',
  'Makung',
  'Kinmen',
  'Bushehr',
  'Hail',
  'Kandahar',
  'Palmerston North',
  'Dunedin',
  'Tongatapu',
  "Governor's Harbor",
  'Los Mochis',
  'Durango',
  'Reykjavik',
  'Ciudad Obregon',
  'Whitehorse',
  'Terrace',
  'Van',
  'Erzurum',
  'Williams Lake',
  'Elat',
  'Karlovy Vary',
  'Perugia',
  'Marina Di Campo',
  'Cuneo',
  'Rouyn',
  'Sitia',
  'Limnos',
  'Nea Anghialos',
  'Tours',
  'Perpignan',
  'St-Etienne',
  'Metz',
  'Tarbes',
  'Pau',
  'Melilla',
  'Blantyre',
  'Goroka',
  'Quinhagak',
  'Wales',
  'Elim',
  'Tanana',
  'Gjoa Haven',
  'Ruby',
  'Sandnessjoen',
  'Mosjoen',
  'Floro',
  'Ganja',
  'Flin Flon',
  'Tobruk',
  'Mo i Rana',
  'Big Trout Lake',
  'Kiunga',
  'Gizo',
  'Hodeidah',
  'Helena',
  'Bettles',
  'Tachilek',
  'Kingstown',
  'Scarborough',
  'Arica',
  'Raiatea Island',
  'Quepos',
  'Sibiu',
  'Vilankulu',
  'Maroantsetra',
  'Daocheng',
  'Nosy-be',
  'Jiagedaqi District',
  'Kasane',
  'Beloyarsky',
  'Johannesburg',
  'Bloemfontein',
  'Parauapebas',
  'Araguaina',
  'Vilhelmina',
  'Postville',
  'St. Michael',
  'Lycksele',
  'White Mountain',
  'Golovin',
  'Brevig Mission',
  'Noorvik',
  'Kramfors',
  'Kiana',
  'Buckland',
  'Ambler',
  'Thorne Bay',
  'Toowoomba',
  'Huslia',
  'Montreal',
  'Russian Mission',
  'Hilton Head',
  'Hamilton',
  'Branson',
  'Choibalsan',
  'St-Augustin',
  'Deering',
  'Puvirnituq',
  'Savoonga',
  'Point Hope',
  'Gambell',
  'Panzhihua',
  'Yining',
  'Batsfjord',
  'Enshi',
  'Groote Eylandt',
  'Gladstone',
  'Vagar',
  'Broken Hill',
  'Haiphong',
  'Bugulma',
  'Nukus',
  'Izhevsk',
  'Nyagan',
  'Kingman',
  'Spanish Town',
  'San Cristóbal',
  'Santa Maria',
  'Macaé',
  'Fukushima',
  'Londolovit',
  'Kalskag',
  'Hiva-oa',
  'Puerto Jimenez',
  'Nicoya',
  'Cockburn Town',
  'San Luis Obispo',
  'Grand Island',
  'Albany',
  'Nanyuki',
  'Galcaio',
  'Bosaso',
  'El Aaiún',
  'Mpumalanga',
  'Fredericton',
  'Sogndal',
  'Kumasi',
  'Batna',
  'Muskrat Dam',
  'Chevery',
  'Hopedale',
  'Makkovik',
  'Nain',
  'Apartadó',
  'Chisasibi',
  'Bearskin Lake',
  'Nanortalik',
  'Tabubil',
  'Kavieng',
  'Daru',
  'Buka Island',
  'Munda',
  'Oulu',
  'Mariehamn',
  'Naryan-Mar',
  'Ukhta',
  'Kzyl-Orda',
  'Berlevag',
  'Orsta-Volda',
  'Copiapo',
  'Ciudad del Este',
  'Erie',
  'Vineyard Haven MA',
  'Ozamis',
  'Legazpi',
  'Dipolog',
  'Butuan',
  'Astypalaia',
  'Binghamton',
  'Idaho Falls',
  'Hue',
  'El Calafate',
  'Manhattan',
  'Champaign',
  'Rochester',
  'Uluru',
  'Caticlan',
  'Surat Thani',
  'Clyde River',
  'Ithaca',
  'Lewiston',
  'Labuhan Bajo',
  'Ende',
  'Tanjung Pandan',
  'Kendari',
  'Youngstown',
  'Watertown',
  'Columbia',
  'Laredo',
  'Salisbury',
  'Luebeck',
  'Duluth',
  'Hilo',
  "Coff's Harbour",
  'Albury',
  'Charlieville',
  'Dili',
  'Labuan',
  'Gorontalo',
  'Timika',
  'Biak',
  'Myitkyina',
  'Stavropol',
  'Makhachkala',
  'Abakan',
  'Bratsk',
  'Aguadilla',
  'St. Martin',
  'Santo Domingo',
  'Maturin',
  'Paraguana',
  'Bagotville',
  'Yacuiba',
  'Santa Marta',
  'Cucuta',
  'Puerto Asis',
  'Balmaceda',
  'Uberaba',
  'Bahia Blanca',
  'Iguazu Falls',
  'Dumaguete',
  'Ghardaia',
  'Kwangju',
  'Biskra',
  'Hanamaki',
  'Kochi',
  'Fukue',
  'Hualien',
  'Kiritimati',
  'Majuro',
  'Abu Dhabi',
  'Tamanrasset',
  'Kerman',
  'Sault Sainte Marie',
  'Mazar-i-sharif',
  'Nelson',
  'Hamilton',
  'Huahine Island',
  'Nuku Hiva',
  'Cockburn Town',
  'Spence Bay',
  'Mexicali',
  'Charlottetown',
  'Smithers',
  'Pangnirtung',
  'Malatya',
  'Sivas',
  'Cranbrook',
  'Pico',
  'Flores',
  'Ostrava',
  'Parma',
  'Hall Beach',
  'Repulse Bay',
  'Kasos',
  'Kithira',
  'Nimes',
  'Caen',
  'Fort Smith',
  'Rodez',
  'Quesnel',
  'Grande Prairie',
  'Osijek',
  'Lamu',
  'Aswan',
  'Nouadhibou',
  'Bulawayo',
  'Sao Tome',
  'Masai Mara',
  'Kotlik',
  'Kwigillingok',
  'Emmonak',
  'Bonaventure',
  'Samburu South',
  'Sege',
  'Nicoya',
  'Anaktuvuk Pass',
  'Dryden',
  'Andoya',
  'Longreach',
  'Haines',
  'Skagway',
  'Craig Cove',
  'Pikangikum',
  'Inukjuak',
  'Stokmarknes',
  'Ikaria',
  'Lanai',
  'Molokai',
  'Fak Fak',
  'Dzhambul',
  'Pelotas',
  'Altamira',
  'Campos',
  'Moorea',
  'Golfito',
  'Konya',
  'Tirgu Mures',
  'Valladolid',
  'Eldoret',
  'Quelimane',
  'Inhambane',
  'Lubango',
  'Soyo',
  'Menongue',
  'Huambo',
  'Toliara',
  'Sambava',
  'Mahajanga',
  'Antalaha',
  'Sigiriya',
  'Sainte Marie',
  'St.-pierre',
  'Moosonee',
  'Brusselton',
  'Bangui',
  'Yongzhou',
  'Bauru',
  'Toksook Bay',
  'Baise',
  'Mackenzie British Columbia',
  'Ukunda',
  'Waterloo',
  'Provo',
  'Zhijiang',
  'Liping',
  'Pond Inlet',
  'Jijiga',
  'Joacaba',
  'Dourados',
  'Sinop',
  'Cabo Frio',
  'Vasteras',
  'Bella Bella',
  'Skelleftea',
  'Havre-Saint-Pierre',
  'St. George',
  'Kiruna',
  'Grayling',
  'Tuluksak',
  'Akiak',
  'Pilot Station',
  'Kongiganak',
  'Klawock',
  'Kipnuk',
  'Hay River',
  'Teller',
  'Kobuk',
  'Metakatla',
  'Hoonah',
  'Shungnak',
  'Nulato',
  'Kwethluk',
  'Eek',
  'Shageluk',
  'Kalkmar',
  'Alliance',
  'Chadron',
  'Corozal',
  'Chefornak',
  'Puntarenas',
  'Mohe County',
  'Ronneby',
  'Marquette',
  'Holman Island',
  'Mus',
  'Walvis Bay',
  'Punta del Este',
  'Chaoyang',
  'Wuzhou',
  'La Fortuna/San Carlos',
  'Shishmaref',
  'Kivalina',
  'Kaltag',
  'Anvik',
  'Stord',
  'Svalbard',
  'Iles De La Madeleine',
  'Heihe',
  'Bangda',
  'Zhaotong',
  'Simao',
  'Burnie',
  'Roma',
  'Paraburdoo',
  'Mornington Island',
  'Moranbah',
  'Maningrida',
  'Merimbula',
  'Lord Howe Island',
  'Geraldton',
  'Doomadgee',
  'Albany',
  'Lawas',
  'Langgur-Kei Islands',
  'Tanjung Redep-Borneo Island',
  'Waikabubak-Sumba Island',
  'La Grande Riviere',
  'Pleiku',
  'Phucat',
  'Can Tho',
  'Gan Island',
  'Andizhan',
  'Kirov',
  'Kostanay',
  'El Vigía',
  'Puerto Inírida',
  'Esmeraldas',
  'Roxas City',
  'Tuguegarao',
  'Sangley Point',
  'Sacheon',
  'Holy Cross',
  'Gustavus',
  'Uromiyeh',
  'Ardabil',
  'Ipota',
  'Gaua Island',
  'Lonorore',
  'Loh/Linua',
  'Sola',
  'Ablow',
  'Ua Huka',
  'Ua Pou',
  'Savusavu',
  'Matei',
  "Arthur's Town",
  'La Isabela',
  'Kahramanmaras',
  'Kars',
  'Banja Luka',
  'Worland',
  'Valdosta',
  'Rock Springs',
  'Latrobe',
  'Brunswick',
  'Watertown',
  "Al Bayda'",
  'Essadouira',
  'Dakhla',
  'Windhoek',
  'Ängelholm',
  'Östersund',
  'Bydgoszcz',
  'Vardø',
  'Svolvær',
  'Rørvik',
  'Namsos',
  'Leknes',
  'Papa Westray',
  'North Ronaldsay',
  'Sandy Lake',
  'Sanikiluaq',
  'Umiujaq',
  'Chibougamau',
  'Aupaluk',
  'Fort Hope',
  'Lourdes-De-Blanc-Sablon',
  'Kangirsuk',
  'Sisimiut',
  'Qaanaaq',
  'Vanimo',
  'Tari',
  'Moro',
  'Kirakira',
  'Teesside',
  'Pori',
  'Lappeenranta',
  'Arcata CA',
  'Uraj',
  'Anapa',
  'Kruunupyy',
  "ST MARY\\\\'S",
  'Gillette',
  'Columbus Mississippi',
  'Columbus',
  'Busuanga',
  'NAPIER',
  'Nauru',
  'La Crosse',
  'Flores',
  'Aasiaat',
  'Tagbilaran',
  'Palanga',
  'Ubon Ratchathani',
  'Bima',
  'Palangkaraya',
  'Tanjung Pinang',
  'Malang',
  'Casper',
  'Unalaska',
  'Sitka',
  'Tyler',
  'Dothan',
  'Brownsville',
  'College Station',
  'Cincinnati',
  'Kenai',
  'Cordova',
  'Yuma',
  'Lincoln',
  'Lake Charles',
  'Huron',
  'Dillingham',
  'St. Paul Island',
  'Wagga Wagga',
  'Dubbo',
  'Learmonth',
  'Prosserpine',
  'Merauke',
  'Nabire',
  'Sittwe',
  'Phitsanulok',
  'Rajahmundry',
  'Vijayawada',
  'Savannakhet',
  'Jessore',
  "Cox's Bazar",
  'Surat',
  'Rajkot',
  'Jabalpur',
  'Tozeur',
  'Kemorovo',
  'Barnaul',
  'Semiplatinsk',
  'Pavlodar',
  'Uralsk',
  'Puerto Maldonado',
  'Pasto',
  'Puerto Carreno',
  'Mitu',
  'Monteria',
  'Ibague',
  'Cuenca',
  'Coca',
  'Temuco',
  'Enugu',
  'Sao Jose Dos Campos',
  'Macapa',
  'Montes Claros',
  'Ipatinga',
  'Fernando Do Noronha',
  'Caxias Do Sul',
  'Cascavel',
  'Boa Vista',
  'Mar Del Plata',
  'Tamale',
  'Esquel',
  'St. Anthony',
  'Cotabato',
  'Pohang',
  'Ulsan',
  'Yeosu',
  'Yamagata',
  'Kitakyushu',
  'Tsushima',
  'Yamaguchi',
  'Obihiro',
  'Pohnpei',
  'Kwajalein',
  'Rahim Yar Khan',
  'Gwadar',
  'Nejran',
  'Bisha',
  'El-baha',
  'Al-ahsa',
  'Woodbourne',
  'Tauranga',
  'Rotorua',
  'New Plymouth',
  'Lifou',
  'Maupiti',
  'Manihi',
  'Wallis',
  'Tarawa',
  'Camaguey',
  'Cap Haitien',
  'Palmar Sur',
  'Puerto Escondido',
  'Colima',
  'Tepic',
  'Fort Nelson',
  'Ciudad Del Carmen',
  'Huatulco',
  'Batman',
  'Erzincan',
  'Porto Santo',
  'Santa Maria (island)',
  'Tel-aviv',
  'Rimini',
  'Pantelleria',
  'Lampedusa',
  'Skiros',
  'Patras',
  'Alexandroupolis',
  'St.-pierre',
  'Hyeres',
  'Dinard',
  'Cape Dorset',
  'St. John',
  'Dole',
  'Castres',
  'Gander',
  'San Sebastian',
  'Kufra',
  'Kenora',
  'Windsor',
  'Red Deer Industrial',
  'Makale',
  'Lalibella',
  'Dire Dawa',
  'Hierro',
  'Kananga',
  'Goma',
  'Cabinda',
  'Tununak',
  'Nightmute',
  'Ravensthorpe',
  'Allakaket',
  'Noatak',
  'Erechim',
  'Seattle',
  'Esperance',
  'Saga',
  'Dera Ghazi Khan',
  'Ambryn Island',
  'Ahe',
  'New Bedford',
  'Clarksburg',
  'Sorkjosen',
  'Sanday',
  'Round Lake',
  'Fort Severn',
  'Fort Frances',
  'Wunnumin Lake',
  'Angling Lake',
  'Punta Gorda',
  'Narsaq',
  'Forde',
  'Springfield',
  'Honningsvag',
  'Kemi',
  'Jyvaskyla',
  'Barnstable',
  'Maumere',
  'El Dorado',
  'Norfolk Island',
  'Kaimana',
  'Cobija',
  'In Salah',
  'Takaroa',
  'Tikehau',
  'Tubuai',
  'Rurutu',
  'Aitutaki',
  'Cayman Barac',
  'Cayo Largo del Sur',
  'Bocas Del Toro',
  'Kisumu',
  'Kisangani',
  'Mbandaka',
  'High Level',
  'Lichinga',
  'Saurimo',
  'Malanje',
  'Kuito',
  'Tolagnaro',
  'Xiahe city',
  'Bingol',
  'Morondava',
  'Igdir',
  'Garoua',
  'Sir Bani Yas Island',
  'Bodaibo',
  'Bata',
  'Kooddoo',
  'Lankaran',
  'Francistown',
  'Upington',
  'Al-Ula',
  'Cacador',
  'Arctic Bay',
  'Kegaska',
  'Newtok',
  'Juiz de Fora',
  'Friday Harbor',
  'Westsound',
  'Roche Harbor',
  'Kimberley',
  'NAYPYITAW',
  'Hoedspruit',
  'Zhongwei',
  'Shiquanhe',
  'Yushu',
  'Sevastopol',
  'Zonguldak',
  'Latacunga',
  'Morristown',
  'Rundu',
  'Santa Ana',
  'Ulawa',
  'Itaituba',
  'Wenshan',
  'Lincang',
  'Baoshan',
  'Okha',
  'Foshan',
  'Raivavae',
  'Norrkoeping',
  'Linkoeping',
  'Borlange',
  'La Chorrera',
  'Saravena',
  'Rerrenabaque',
  'Orebro',
  'Arvidsjaur',
  'Rainbow Lake',
  'Kangiqsujuaq',
  'Sleetmute',
  'Wainwright',
  'Nunapitchuk',
  'Koyukuk',
  'Nunam Iqua',
  'Alakanuk',
  'Selawik',
  'Ouzinkie',
  'Sveg',
  'Beaver',
  'Venetie',
  'Hughes',
  'Chalkyitsik',
  'Tuntutuliak',
  'Marshall',
  'Kasigluk',
  'Nuiqsut',
  'Mammoth Lakes',
  'Dickinson',
  'Jamestown',
  'Ulyanovsk',
  'Aspen',
  'Mora',
  'Osubi',
  'Greenville',
  'Lewisburg',
  'Brainerd',
  'Altay',
  'Rimatara',
  'Ust-Kut',
  'Bellona',
  'Joenkoeping',
  'Iron Mountain',
  'Yakutat',
  'Taree',
  'Mpacha',
  'Long Akah',
  'Geneina',
  'Kangra',
  'Tacheng',
  'Sand Point',
  'Gorakhpur',
  'Araracuara',
  'Hagerstown',
  'Pajala',
  'Imo',
  'Tasiujaq',
  'Hooper Bay',
  'Atqasuk',
  'Lakselv',
  'Hasvik',
  'Worcester',
  'Karamay',
  'Kuqa',
  'Muren',
  'Bayankhongor',
  'Golmud',
  'Winton',
  'Windorah',
  'St George',
  'Quilpie',
  'Pormpuraaw',
  'Port Lincoln',
  'Parkes',
  'Newman',
  'Normanton',
  'Narrandera',
  'Mount Gambier',
  'Moruya',
  'Gaspe',
  'Lockhart River',
  'Kowanyama',
  'King Island',
  'Julia Creek',
  'Griffith',
  'Cunnamulla',
  'Bathurst',
  'Boulia',
  'Burketown',
  'Bedourie',
  'Birdsville',
  'Aurukun',
  'Laut Island',
  'Kudat',
  'Bario',
  'Mukah',
  'Long Seridan',
  'Long Datih',
  'Dawei',
  'Conson',
  'Laamu Atoll',
  'Haa Dhaalu Atoll',
  'Dimapur',
  'Koggala',
  'Hubli',
  'Saransk',
  'Cheboksary',
  'Vorkuta',
  'Termez',
  'Kurgan',
  'Novokuznetsk',
  'Ivano-Frankivsk',
  'Zaporozhye',
  'Esbjerg',
  'Anadyr',
  'Tiksi',
  'Cherskiy',
  'Chokurdah',
  'Zhezkazgan',
  'Petropavlosk',
  'Kokshetau',
  'Ji-Paraná',
  'Huánuco',
  'Cajamarca',
  'Yopal',
  'Waterford',
  'La Toma (Catamayo)',
  'Marília',
  'Catarman',
  'Basco',
  'Naga',
  'Kunsan',
  'Fort Simpson',
  'Wrangell',
  'Chevak',
  'Mountain Village',
  'Dera Ismael Khan',
  'Chitral',
  'Al Ain',
  'Noshahr',
  'Al-Jawf',
  'Dawadmi',
  'Tiga',
  'Futuna Island',
  "Dillon's Bay",
  'Aniwa',
  'Malekula Island',
  'Lamen Bay',
  'Lamap',
  'Paama Island',
  'Longana',
  'Lambasa',
  'Vunisea',
  'Colonel Hill',
  'Jalapa',
  'Puerto Lempira',
  'Adiyaman',
  'Agri',
  'Corvo',
  'Syros Island',
  'Tupelo',
  'Santa Maria',
  'Rhinelander',
  'Owensboro',
  'North Bend',
  'Lynchburg',
  'Klamath Falls',
  'Lebanon',
  'Hot Springs',
  'Du Bois',
  'Crescent City',
  'Burlington',
  'Bradford',
  'Alpena',
  'Waterloo',
  'Diu',
  'Nyala',
  'Sirt',
  'Tshikapa',
  'Catumbela',
  'Solwesi',
  'Hemavan',
  'Torsby',
  'Karlstad',
  'Hagfors',
  'Sandane',
  'Røst',
  'Dongloe',
  'Westray',
  'Stronsay',
  'Churchill Falls',
  'Sachigo Lake',
  'Kashechewan',
  'Eastmain River',
  'Salluit',
  'Webequie',
  'Wemindji',
  'Lansdowne House',
  'Akulivik',
  'Ivujivik',
  'Nemiscau',
  'Quaqtaq',
  'Gillam',
  'Fort Albany',
  'Attawapiskat',
  'Kasabonika',
  'Cat Lake',
  'La Tabatière',
  'Tête-à-la-Baleine',
  'Poplar Hill',
  'Kingfisher Lake',
  'North Spirit Lake',
  'Rigolet',
  'Uummannaq',
  'Maniitsoq',
  'Paamiut',
  'Neerlerit Inaat',
  'Alluitsup Paa',
  'Misima Island',
  'Ramata',
  'Kagau Island',
  'Suavanao',
  'Rennell Island',
  'Benbecula',
  'Wick',
  'Hawarden',
  'Alderney',
  'Dawson Creek',
  'Savonlinna',
  'Rovaniemi',
  'Dubuque IA',
  'Austin TX',
  'Kittila',
  'Usinsk',
  'Joplin',
  'Cody',
  'Kajaani',
  'Little Cayman',
  'Morgantown',
  'Saint Cloud',
  'Flagstaff',
  'Lawton',
  'Fort Good Hope',
  'Tulita',
  'Deline',
  'Kaadedhdhoo',
  'Bundaberg',
  'Caldas Novas',
  'Laoag',
  'Kastelorizo',
  'Paros',
  'Cyclades Islands',
  'Milos',
  'Johnstown',
  'Tartu',
  'Tuy Hoa',
  'Chu Lai',
  'Dong Hoi',
  'Petersburg',
  'Nan',
  'Victoria',
  'Saint George',
  'Armidale',
  'Franklin',
  'Hervey Bay',
  'Decatur',
  'Jacksn Hole',
  'Redang',
  'New Haven',
  'Kassel',
  'Emerald',
  'Nevsehir',
  'Socotra',
  'Pullman',
  'Khon Kaen',
  'Nakhon Phanom',
  'Nakhon Si Thammarat',
  'Florence',
  'Valdez',
  'Lahania-kapalua',
  'Texarkana',
  'Macon',
  'Sioux City',
  'Roswell',
  'Seattle',
  'Abilene',
  'San Angelo',
  'Jackson',
  'Waco',
  'Altoona',
  'Imperial',
  'Wichita Falls',
  'Columbus',
  'Homer',
  'Williston',
  'Beaumont',
  'Charlo',
  'Williamsport',
  'International Falls',
  'Presque Isle',
  'Garden City',
  'Longview',
  'Harrison',
  'Point Lay',
  'Barter Island',
  'Castlegar',
  'Christmas Island',
  'Weipa',
  'Ipoh',
  'Kerteh',
  'Nanaimo',
  'Ketapang',
  'Luwuk',
  'Thandwe',
  'Myeik',
  'Trang',
  'Pattaya',
  'Tirupeti',
  'Allahabad',
  'Agra',
  'Porbandar',
  'Bhaunagar',
  'Bhuj',
  'Antwerp',
  'Magnetiogorsk',
  'Gabes',
  'Ponce',
  'Valera',
  'Puerto Cabello',
  'Merida',
  'Barinas',
  'Piura',
  'Tacna',
  'Ayacucho',
  'Potosi',
  'Valledupar',
  'Arauca',
  'Tame',
  'San Vincente De Caguan',
  'San Jose Del Guaviare',
  'Neiva',
  'Guapi',
  'Florencia',
  'Corozal',
  'Buenaventura',
  'Armenia',
  'Galapagos',
  'Valdivia',
  'Easter Island',
  'Calabar',
  'Benin',
  'Rio Grande',
  'Santo Angelo',
  'Campina Grande',
  'President Prudente',
  'Criciuma',
  'Aracatuba',
  'Takoradi',
  'Rio Grande',
  'Jujuy',
  'Bobo-dioulasso',
  'San Julian',
  'Tucuman',
  'San Rafael',
  'Santa Fe',
  'Zarzaitine',
  'Parana',
  'Pagadian',
  'El Golea',
  'Misawa',
  'Tokushima',
  'Amami',
  'Iki',
  'Wakkanai',
  'Nakashibetsu',
  'Matsumoto',
  'Yap',
  'Kosrae',
  'Chuuk',
  'Rota',
  'Tilrempt',
  'Zhob',
  'Moenjodaro',
  'Faisalabad',
  'Aqaba',
  'Ramsar',
  'Birjand',
  'Bandar Lengeh',
  'Bandar Mahshahr',
  'Sharurah',
  'Arar',
  'Hafr Al-batin',
  'Guriat',
  'Whangarei',
  'Paraparaumu',
  'Invercargill',
  'Gisborne',
  'Taupo',
  'Ouvea',
  'Port Hardy',
  'Koumac',
  'Mataiva',
  'Fakarava',
  'Mayaguana',
  'Stella Maris',
  "Dead Man's Cay",
  'Matthew Town',
  'Rock Sound',
  'Alice Town',
  'Treasure Cay',
  'Spring Point',
  'David',
  'Tapachula',
  'Uruapan',
  'Piedras Negras',
  'Minatitlan',
  'Matamoros',
  'Lazard Cardenas',
  'Saltillo',
  'Ciudad Victoria',
  'Campeche',
  'North Bay',
  'South Caicos',
  'Abbotsford',
  'Denizli',
  'Merzifon',
  'Altenrhein',
  'Lugano',
  'Satu Mare',
  'Oradea',
  'Craiova',
  'Baia Mare',
  'Sao Jorge Island',
  'Haifa',
  'Pardubice',
  'Bolzano',
  'Broughton Island',
  'Debrecen',
  'Skiathos',
  'Ioannina',
  'Lorient',
  'Deauville',
  'Sachs Harbour',
  'Chalons',
  'Avignon',
  'Resolute',
  'Perigueux',
  'Agen',
  'Sydney',
  'Badajoz',
  'Plovdiv',
  'El Fasher',
  'Gondar',
  'Axum',
  'Sao Nocolau Island',
  'Fort Chipewyan',
  'Prince Pupert',
  'Ouarzazate',
  'Monrovia',
  'Port Menier',
  'Mbuji-mayi',
  'Kindu',
  'Bukavu/kavumu',
  'Bunia',
  'Thule',
  'Oriximina',
  'Ourilandia do Norte',
  'Patos de Minas',
  'Choiseul Bay',
  'Crooked Creek',
  'Coffman Cove',
  'Scammon Bay',
  'Port Lions',
  'Old Harbor',
  'Weyers Cave',
  'Bella Coola',
  'Flinders Island',
  'Coen',
  'Tufi',
  'Waala',
  'Atiu Island',
  'Beckley',
  'Amboseli National Park',
  'Eday',
  'Bathurst',
  'Deer Lake',
  'Fera Island',
  'Ivalo',
  'Saba',
  'Blackall',
  'Al Ghaidah Intl',
  'Saidpur',
  'Gafsa',
  'San Luis',
  'Ghriss',
  'Tiaret',
  'Djanet',
  'Hao Island',
  'Kapuskasing',
  'Pamplona',
  'Lodwar',
  'Asosa',
  'Jimma',
  'Gambella',
  'Bahar Dar',
  'Arba Minch',
  'Ziguinchor',
  'Praslin',
  'Port Gentil',
  'Luena',
  "M'banza-congo",
  'Kastamonu',
  'Mananara',
  'Mamuju',
  'Thanh Hoa',
  'Mfuwe',
  'Kutahya',
  "N'gaoundere",
  'Maroua',
  'Dalma Island',
  'Rodriguez Island',
  'Veliky Ustyug',
  'Kangding',
  'Rio Hondo',
  'Manzini',
  'Yuzhno-Kurilsk',
  'Qabala',
  'Gorno-Altaysk',
  'Pomalaa',
  'Umtata',
  'Lloydminster',
  'Lephalale',
  "Richard's Bay",
  'Pietermaritzburg',
  'Polokwane',
  'Phalaborwa',
  'Keewaywin',
  'Margate',
  'Santa Isabel do Rio Negro',
  'Sao Paulo de Olivenca',
  'Eirunepe',
  'Sao Felix do Araguaia',
  'Bointo',
  'Redencao',
  'Trail',
  'Vinnitsa',
  'Ittoqqortoormiit',
  'Mulatupo',
  'Garachine',
  'Achutupo',
  'Goodnews Bay',
  'Puerto Obaldia',
  'El Porvenir',
  'Playon Chico',
  'Marktoberdorf',
  'Mysore',
  'Stephenville',
  'Los Alamos',
  'Dickwella',
  'Ulaangom',
  'Yasuj',
  'Sao Gabriel da Cachoeira',
  'Longyan',
  'Iturup Island',
  'Olgii',
  'Lleida',
  'Pakuba',
  'Guanambi',
  'Barcelos',
  'Coari',
  'Araxa',
  'Rio Verde',
  'Guarapuava',
  'Rondonopolis',
  'Minacu',
  'Parintins',
  'Gurupi',
  'Villa Garzon',
  'La Macarena',
  'Uyuni',
  'Christiansted',
  'Manley Hot Springs',
  'Kake',
  'Healy',
  'Stony River',
  'Red Devil',
  'Circle',
  'Ornskoldsvik',
  'Takotna',
  'Nikolai',
  'Nelson Lagoon',
  'False Pass',
  'Nikolski',
  'Atka',
  'Tin City',
  'Seal Bay',
  'Kitoi Bay',
  'Amook Bay',
  'Larsen Bay',
  'Akhiok',
  'South Naknek',
  'Pilot Point',
  'Perryville',
  'Chignik Lagoon',
  'Egegik',
  'Chignik Lake',
  'North Whale Pass',
  'Port Protection',
  'Point Baker',
  'Hydaburg',
  'Excursion Inlet',
  'Pelican',
  'Tenakee Springs',
  'Elfin Cove',
  'Angoon',
  'Merced',
  'Visalia',
  'Coldfoot',
  'Brich Creek',
  'Central',
  'Rampart',
  'Minto',
  'Levelock',
  'Chuathbaluk',
  'Eastsound',
  'Friday Harbor',
  'Vernal',
  'Moab',
  'Wolf Point',
  'Glendive',
  'McCook',
  'Sidney',
  'Manistee',
  'Gunnison',
  'Gelendzik',
  'Kristianstad',
  'Thief River Falls',
  'St. Augustine Airport',
  'Yaroslavl',
  'Trollhattan',
  'Wenatchee',
  'Pendleton',
  'Riverton WY',
  'Montrose CO',
  'Marion',
  'Culebra Island',
  'Escanaba',
  'Orange',
  'Grafton',
  'Hamadan',
  'Çorlu',
  'Sinop',
  'Canakkale',
  'Eskissehir',
  'Walaha',
  'Tanjung Manis',
  'Togiak Village',
  'Port Heiden',
  'King Cove',
  'Igiugig',
  'Burgos',
  'Leon',
  'Lago Agrio',
  'Parsabad',
  'Ilam',
  'Governador Valadares',
  'Apatity',
  'Cauayan',
  'Arctic Village',
  'Mekoryuk',
  'Skien',
  'Roros',
  'Orland',
  'Tambow',
  'Provincetown',
  'Boulder City',
  'Grand Canyon West',
  'Fagernes',
  'Bardufoss',
  'Khovd',
  'Altai',
  'Whyalla',
  'Thargomindah',
  'Cocos Keeling Island',
  'Argyle',
  'Olympic Dam',
  'Moree',
  'McArthur River Mine',
  'Milingimbi',
  'Lismore',
  'Horn Island',
  'Elcho Island',
  'Devonport',
  'Ceduna',
  'Coober Pedy',
  'Barcaldine',
  'Ranai-Natuna Besar Island',
  'Bakalalan',
  'Kawthoung',
  'Dienbienphu',
  'Soenderborg',
  'Tak',
  'Nepalgunj',
  'Chandragarhi',
  'Ronne',
  'Bharatpur',
  'Barisal',
  'Shillong',
  'Penza',
  'Orsk',
  'Kursk',
  'Lopez',
  'Silver City',
  'Akutan',
  'Greenville',
  'Kearney',
  'Elista',
  'Beslan',
  'Grozny',
  'Igarka',
  'Karup',
  'Kyzyl',
  'Petrozavodsk',
  'Solovetsky Islands',
  'Uzhgorod',
  'Kingston',
  'Nakhchivan',
  'Santa Rosa',
  'Riberalta',
  'Guayaramerín',
  'Nuquí',
  'La Pedrera',
  'Puerto Leguízamo',
  'Lençóis',
  'Masbate',
  'Calbayog City',
  'Virac',
  'Jolo',
  'Camiguin',
  'Sokcho / Gangneung',
  'Wonju',
  'Shonai',
  'Odate Noshiro',
  'Iwami',
  'Losuia',
  'Adak Island',
  'Boca de Sábalo',
  'Contadora Island',
  'Bahia Piña',
  'Skardu',
  'Dalbandin',
  'Sabzevar',
  'Bojnourd',
  'Bam',
  'Khorram Abad',
  'Île des Pins',
  'Anelghowhat',
  'Valesdir',
  'Tongoa Island',
  'Maewo Island',
  'Pentecost Island',
  'Sangafa',
  'Futuna Island',
  'Vanua Balavu',
  'Rotuma',
  'Lakeba Island',
  'Cicia',
  'Mitiaro Island',
  'Mauke Island',
  'Mangaia Island',
  'Long Banga',
  'San Jose',
  'Roxana',
  'Jaqué',
  'Salt Cay',
  'Ubari',
  'Balikesir Korfez',
  'Isparta',
  'Mount Pleasant',
  'Logroño-Agoncillo',
  'Yakima',
  'Victoria',
  'Quincy',
  'Salina',
  'Saranac Lake',
  'Sheridan',
  'Rutland',
  'Portsmouth',
  'Pellston',
  'Pocatello',
  'Hattiesburg/Laurel',
  'Muscle Shoals',
  'Muskegon',
  'Lancaster',
  'North Platte',
  'Laramie',
  'Kirksville',
  'Glasgow',
  'Elko',
  'Eau Claire',
  'Hancock',
  'Port Angeles',
  'Sault Ste Marie',
  'Cape Girardeau',
  'Scottsbluff',
  'Walla Walla',
  'Athens',
  'Aberdeen',
  'Arua',
  'Bukoba',
  'Lokichoggio',
  'Gode',
  'Sao Filipe',
  'La Gomera',
  'Oranjemund',
  'Ondangwa',
  'Luderitz',
  'Chimoio',
  'Mocamedes',
  'Chipata',
  'Shire Indasilase',
  'Barra',
  "Land's End",
  'Campbeltown',
  'Guemar',
  'Bordj Badji Mokhtar',
  'Béchar',
  'Masset',
  'Gamètì',
  'Powell River',
  'Peawanuck',
  'Kangiqsualujjuaq',
  "Lutselk'e",
  'Kimmirut',
  'Grise Fiord',
  'Tarapacá',
  'Ogoki Post',
  'Summer Beaver',
  'Whatì',
  'Anahim Lake',
  'Wapenamanda',
  'Mendi',
  'Kundiawa',
  'Tiree',
  'Marau',
  'Santa Cruz/Graciosa Bay/Luova',
  'Atoifi',
  'Dundee',
  'Islay',
  'Golouchestershire',
  'Kuopio',
  'Kogalym',
  'Kuusamo',
  'Narvik',
  'Hayden',
  'Cortez',
  'Meridian',
  'Georgetown',
  'Chumphon',
  'Joensuu',
  'Bemidji',
  'Monaco',
  'Twin Falls',
  'Vail',
  'Paulatuk',
  'Grand Canyon',
  'Dhangarhi',
  'Tumling Tar',
  'Brac',
  'Pai',
  'Ca Mau',
  'Rach Gia',
  'Muang Xay',
  'Luang Namtha',
  'Trat',
  'Ranong',
  'Buri Ram',
  'Roi Et',
  'Kuressaare',
  'Santa Elena de Uairen',
  'PADUCAH',
  'PARKERSBURG',
  'Vancouver',
  'Redding',
  'Sihanoukville',
  'Carlsbad',
  'Mae Hong Son',
  'Phon Savan',
  'Funafuti',
  'Kingscote',
  'Rockland',
  'Bar Harbor',
  'Butte',
  'Naples',
  'Ataq',
  'Gyumri',
  'Sukhothai',
  'Waingapu',
  'Naha',
  'Topeka',
  'Cedar City',
  'Modesto',
  'Stockton',
  'Belleville',
  'Hobbs',
  'Augsburg',
  'Ogdensburg',
  'Chico',
  'Augusta',
  'Fort Leonardwood',
  'Hibbing',
  'Teterboro',
  'Hamburg',
  'San Luis',
  'Havre',
  'Carlsbad',
  'Jonesboro',
  'Mannheim',
  'Massena',
  'Kamuela',
  'Pueblo',
  'Prescott',
  'Hana',
  'Port Moller',
  'Iliamna',
  'Tatalina',
  'Cape Lisburne',
  'Wajima',
  'Tamworth',
  'Richmond',
  'Melbourne',
  'Avalon',
  'Amberley',
  'Lahad Datu',
  'Limbang',
  'Babo',
  'Poso',
  'Wamena',
  'Putao',
  'Kyaukpyu',
  'Kengtung',
  'Loei',
  'Sakon Nakhon',
  'Narathiwat',
  'Phrae',
  'Lampang',
  'Agatti Island',
  'Biratnagar',
  'Pokhara',
  'Bhairawa',
  'Ludhiaha',
  'Kanpur',
  'Ostend',
  'Brandon',
  'Gwalior',
  'Kulu',
  'Rajshahi',
  'Trinciomalee',
  'Khajuraho',
  'Jamnagar',
  'Belgaum',
  'Pevek',
  'Oranjestad',
  'Mayaguez',
  'San Tome',
  'San Antonio',
  'Puerto Ayacucho',
  'La Fria',
  'Cumana',
  'Coro',
  'Canaima',
  'Trujillo',
  'Tumbes',
  'Anta',
  'Andahuaylas',
  'Chiclayo',
  'Yola',
  'Sokoto',
  'Rio Hacha',
  'Providencia',
  'Popayan',
  'Manizales',
  'Ipiales',
  'Barrancabermeja',
  'Tumaco',
  'Bahia Solano',
  'Kaduna',
  'Manta',
  'Macas',
  'Jos',
  'Ilorin',
  'Ibadan',
  'Osorno',
  'Vilhena',
  'Uruguaiana',
  'Paulo Alfonso',
  'Tucurui',
  'Tabatinga',
  'Oriximina',
  'Bom Jesus Da Lapa',
  'Cruzeiro do Sul',
  'Corumba',
  'Alta Floresta',
  'Araracuara',
  'Conceicao Do Araguaia',
  'San Martin Des Andes',
  'Santa Rosa',
  'Sunyani',
  'Puerto Madryn',
  'Viedma',
  'Posadas',
  'Formosa',
  'Resistencia',
  'La Rioja',
  'Santiago Del Estero',
  'Catamarca',
  'San Jose',
  'Touggourt',
  'Kumejima',
  'Oshima',
  'Hachijojima',
  'Tottori',
  'Izumo',
  'Monbetsu',
  'Nanki-shirahama',
  'Tainan',
  'Fengnin',
  'Tebessa',
  'Panjgur',
  'Gilgit',
  'Khasab',
  'Fujeirah',
  'Sanandaj',
  'Wejh',
  'Turaif',
  'Rafha',
  'Fort Mcpherson',
  'Wanganui',
  'Westport',
  'Whakatane',
  'Timaru',
  'Kaitaia',
  'Kerikeri',
  'Hokitika',
  'Touho',
  'Mare',
  'Kone',
  'Sarnia',
  'Arutua',
  'Takapoto',
  'Makemo',
  'Kaukura Atoll',
  'Sandspit',
  'Totegegie',
  'Pago Pago',
  'Guantanamo',
  'Nosara Beach',
  'Changuinola',
  'Nuevo Laredo',
  'Loreto',
  'Penticton',
  'Chetumal',
  'Guanaja',
  'Medicine Hat',
  'Constanta',
  'Arad',
  'Mostar',
  'Graciosa Island',
  'Brno',
  'Isafjordur',
  'Kastoria',
  'Tuktoyaktuk',
  'Dijon',
  'Quimper',
  'Lannion',
  'Le Havre',
  'Aurillac',
  'Le Puy',
  'Angouleme',
  'Salamanca',
  'Egilsstadir',
  'Mtwara',
  'Arusha',
  'Kamembe',
  'Ghadames',
  'Lethbridge',
  'Ghat',
  'Kitale',
  'Abu Simbel',
  'Maio',
  'Akureyri',
  'Cap Skiring',
  'Tetouan',
  'Al Hociema',
  'Tan Tan',
  'Pickle Lake',
  'Isiro',
  'Gemena',
  'Maseru',
  'Sao Felix do Xingu',
  'Santa Terezinha',
  'Breves',
  'Santana do Araguaia',
  'Zachar Bay',
  'Port Williams',
  'Karluk',
  'Dalanzadgad',
  'Portland',
  'Alofi',
  'Lodja',
  'Utila',
  'Massawa',
  'Tulcan',
  'Ovda',
  'Kozani',
  'Kalemie',
];

export { destinations };
